### ISSUE TITLE
GENDIS Install problem

### ISSUE THREAD

**Issue by humaun21** [IBCNServices/GENDIS#1]
I am trying to install gendis. But I can't install it. I used 'pip install gendis' in my command prompt.
But It's failed. I am using python 3.6.5

At the end there is this error

"    ----------------------------------------
Command ""c:\users\humaun rashid\anaconda3\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\HUMAUN~1\\AppData\\Local\\Temp\\pip-install-m90pf7zc\\tslearn\\setup.py';f=getattr(tokeni
ze, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\HUMAUN~1\AppData\Local\Temp\pip-record-zwcfs0k2\install-recor
d.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\HUMAUN~1\AppData\Local\Temp\pip-install-m90pf7zc\tslearn\"

**Comment by GillesVandewiele** [comment]
Hello, 

Seems like something went wrong while compiling tslearn, a dependency of GENDIS, but I'm not really sure what... Could you clone the repository and try run `(sudo) python setup.py install`? Or maybe copy-paste the entire log?

**Comment by humaun21** [comment]
Hi
Thanks for you reply
It's not working ....Could you see last line. Do I  need Microsoft Visual C++ 14.0 .??

**C:\Users\GENDIS>python setup.py install**
running install
running bdist_egg
running egg_info
creating GENDIS.egg-info
writing GENDIS.egg-info\PKG-INFO
writing dependency_links to GENDIS.egg-info\dependency_links.txt
writing requirements to GENDIS.egg-info\requires.txt
writing top-level names to GENDIS.egg-info\top_level.txt
writing manifest file 'GENDIS.egg-info\SOURCES.txt'
reading manifest file 'GENDIS.egg-info\SOURCES.txt'
writing manifest file 'GENDIS.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib
creating build\lib\gendis
copying gendis\genetic.py -> build\lib\gendis
copying gendis\mstamp_stomp.py -> build\lib\gendis
copying gendis\util.py -> build\lib\gendis
copying gendis\__init__.py -> build\lib\gendis
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\gendis
copying build\lib\gendis\genetic.py -> build\bdist.win-amd64\egg\gendis
copying build\lib\gendis\mstamp_stomp.py -> build\bdist.win-amd64\egg\gendis
copying build\lib\gendis\util.py -> build\bdist.win-amd64\egg\gendis
copying build\lib\gendis\__init__.py -> build\bdist.win-amd64\egg\gendis
byte-compiling build\bdist.win-amd64\egg\gendis\genetic.py to genetic.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\gendis\mstamp_stomp.py to mstamp_stomp.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\gendis\util.py to util.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\gendis\__init__.py to __init__.cpython-36.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying GENDIS.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying GENDIS.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying GENDIS.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying GENDIS.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying GENDIS.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist\GENDIS-1.0.7-py3.6.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing GENDIS-1.0.7-py3.6.egg
Copying GENDIS-1.0.7-py3.6.egg to c:\users\humaun rashid\anaconda3\lib\site-packages
Adding GENDIS 1.0.7 to easy-install.pth file

Installed c:\users\humaun rashid\anaconda3\lib\site-packages\gendis-1.0.7-py3.6.egg
Processing dependencies for GENDIS==1.0.7
Searching for tslearn==0.1.18.3
Reading https://pypi.org/simple/tslearn/
Downloading https://files.pythonhosted.org/packages/07/da/f93a34e488d6859b780eb55b91193fa823f4118446db7923b32c4a019cb6/tslearn-0.1.18.3.tar.gz#sha256=b312ff133014590068caeb4fa8d0a8e597
aa8289d77a549e36577264e12
Best match: tslearn 0.1.18.3
Processing tslearn-0.1.18.3.tar.gz
Writing C:\Users\HUMAUN~1\AppData\Local\Temp\easy_install-kv492jpx\tslearn-0.1.18.3\setup.cfg
Running tslearn-0.1.18.3\setup.py -q bdist_egg --dist-dir C:\Users\HUMAUN~1\AppData\Local\Temp\easy_install-kv492jpx\tslearn-0.1.18.3\egg-dist-tmp-7o38kgra
**error: Setup script exited with error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools**

**Comment by GillesVandewiele** [comment]
Hmm would seem weird to install an entire development suite, when you probably only need a C++ compiler. Then again, it is Windows...

I cannot really help out much with windows-specific issues, which this one seems to be. You could try to install the C++ suite. The provided link is dead, but [this one](https://visualstudio.microsoft.com/visual-cpp-build-tools/) works. Someone also suggested `pip install --upgrade setuptools`

Hope you can get it to work :)

**Comment by humaun21** [comment]
Hi
Thanks again for your response. Now gendis is successfully installed after installing Microsoft Visual C++ 14.0. 
Now I am trying to run  the Example notebook you provided . But it says  No module named 'data.load_all_datasets'  found(although i installed 'pip install data') and no module 'genetic'  found in my notebook. Should I clone your repository and put it somewhere? If then where?
May be it silly question to ask but I couldn't understand. Could you make me clear this point?
Thanks for your time?

**Comment by humaun21** [comment]
Hi
Now I understand. I put manually data folder inside gendis. Everything works fine.
Now my import is  :+1: 
```
from gendis.data.load_all_datasets import load_data_train_test
from gendis.genetic import GeneticExtractor
```
Have a nice time.

**Comment by GillesVandewiele** [comment]
Cool, glad to hear you got it up and running. And thank you for reporting that  bug, I'll fix it in the nearby future so that you can pip install without cloning the repo.

**Comment by humaun21** [comment]
Hi
Yeah. Nice to hear from you. That must me great.
Best wishes for you.

Best
Rashid
