### ISSUE TITLE
from gendis.genetic import GeneticExtractor and from genetic import GeneticExtractor don't work

### ISSUE THREAD

**Issue by texaspandaa** [IBCNServices/GENDIS#11]
Hi There,

thanks for creating this great package, i am just installed and try to explore it. However when i try to follow the tutorial, i got below error:

>>> from gendis.genetic import GeneticExtractor
Traceback (most recent call last):
  File "C:\Anaconda\envs\te\gendis\genetic.py", line 33, in <module>
    from fitness import logloss_fitness
ModuleNotFoundError: No module named 'fitness'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda\envs\te\gendis\fitness.py", line 6, in <module>
    from gendis.pairwise_dist import _pdist
ModuleNotFoundError: No module named 'gendis.pairwise_dist'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda\envs\te\gendis\genetic.py", line 35, in <module>
    from gendis.fitness import logloss_fitness
  File "C:\Anaconda\envs\te\gendis\fitness.py", line 8, in <module>
    from pairwise_dist import _pdist
ModuleNotFoundError: No module named 'pairwise_dist'

>>> from genetic import GeneticExtractor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'genetic'

 but i am able to import gendis using below and see the private members only of this class, could you please kindly help?

>>> import gendis
>>> gendis.
gendis.__cached__         gendis.__format__(        gendis.__loader__         gendis.__reduce_ex__(
gendis.__class__(         gendis.__ge__(            gendis.__lt__(            gendis.__repr__(
gendis.__delattr__(       gendis.__getattribute__(  gendis.__name__           gendis.__setattr__(
gendis.__dict__           gendis.__gt__(            gendis.__ne__(            gendis.__sizeof__(
gendis.__dir__(           gendis.__hash__(          gendis.__new__(           gendis.__spec__
gendis.__doc__            gendis.__init__(          gendis.__package__        gendis.__str__(
gendis.__eq__(            gendis.__init_subclass__( gendis.__path__           gendis.__subclasshook__(
gendis.__file__           gendis.__le__(            gendis.__reduce__(

best pandaa

**Comment by GillesVandewiele** [comment]
Hi, how did you exactly install it? Through pip or through the setup.py script?

**Comment by texaspandaa** [comment]
hello,
thank u for your reply, i think i used pip to install it. 

Just another question regarding the pso.py, it seems that the ne_shapelets parameter in the extract method is not used by this method, so i can only extrat one shapelet using that method.

best,
pandaa

**Comment by GillesVandewiele** [comment]
Hmm strange, I'm not much of a Windows expert. Maybe you have better luck using `python setup.py install`? I will check later if I can reproduce it, but I am currently travelling abroad.

All code from the `other` directory is a bunch of stuff I once experimented with (with bad code quality). I just uploaded that for completeness and perhaps it could be useful for someone to build further on it. You are completely correct that it will only extract one shapelet as opposed to a set of shapelets.

**Comment by texaspandaa** [comment]
Hello, 
thank you for your reply, the setup.py install works :)

**Comment by GillesVandewiele** [comment]
Great to hear and thanks for reporting this. I will have a closer look at the pip install later :)
