### ISSUE TITLE
Multi-processing

### ISSUE THREAD

**Issue by jmrichardson** [IBCNServices/GENDIS#15]
Hi, your package is great!  One thing is I can't get multiprocessing to work.  I have n_jobs > 1 but it doesn't appear to start more jobs.  I have 50+ cores and just uses one.  Any help is much appreciated.  Thanks:

```
cpus = 30
st = GeneticExtractor(verbose=True, population_size=30, iterations=10, plot=None, n_jobs=cpus)
```

**Comment by GillesVandewiele** [comment]
Hi @jmrichardson 

Thank you for showing interest! That's strange indeed. What OS are you working on?

Note that for now, only the bottle-neck, which is evaluation of all individuals in population (fitness), is parallelized.

**Comment by jmrichardson** [comment]
Hi @GillesVandewiele ,  Sorry, yes I didn't give it enough time.  I am running on redhat 7 and it is working now.  Thanks for the help
