### ISSUE TITLE
Unlabeled data 

### ISSUE THREAD

**Issue by DasNabanita** [IBCNServices/GENDIS#16]
Hi,

I wanted to know if we can extract shapelets with unlabelled time-series data?

Thank you.

**Comment by GillesVandewiele** [comment]
Hi @DasNabanita,

**Short answer:**  Yes, but how do you want to define a "shapelet" in an unsupervised scenario?

**Long answer:**

Thank you for showing interest in GENDIS. Currently, the fitness functions implemented in [fitness.py](https://github.com/IBCNServices/GENDIS/blob/master/gendis/fitness.py) only support supervised classification. Nevertheless, any custom fitness function could be used, including unsupervised things.

The question then becomes: what kind of shapelets are you looking for? With the current implementation of fitness functions, we are looking for shapelets that are able to achieve good classification performance. One example could be that you want to create good clusters (defined by the unsupervised silhouette_score, for example) based on these shapelets? This could be implemented as follows:

```python3
def silhoutte_score(X, y, shapelets, cache=None, verbose=False):
    """Calculate the fitness of an individual/shapelet set"""
    D = np.zeros((len(X), len(shapelets)))

    # First check if we already calculated distances for a shapelet
    for shap_ix, shap in enumerate(shapelets):
        shap_hash = hash(tuple(shap.flatten()))
        cache_val = cache.get(shap_hash)
        if cache_val is not None:
            D[:, shap_ix] = cache_val

    # Fill up the 0 entries
    _pdist(X, [shap.flatten() for shap in shapelets], D)

    # Fill up our cache
    for shap_ix, shap in enumerate(shapelets):
        shap_hash = hash(tuple(shap.flatten()))
        cache.set(shap_hash, D[:, shap_ix])

    km = KMeans(<SOME NUMBER OF CLUSTERS (COULD BE TUNED HERE TOO)>)
    km.fit(D)
    score = -silhouette_score(D, km.predict(D))

    return (score, sum([len(x) for x in shapelets]))
```

You could then just provide some arbitrary labels to the `fit()` function of `GeneticExtractor`, together with this fitness function in its constructor.

**Another unrelated note is that motifs is something that you might want to look into, those are patterns that are often repeated in the data and can be found very efficiently through the Matrix Profiling technique**
